" remove toolbars from gvim
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set go-=L

" enable "full" colors if terminal can display it
if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif

" set syntax highlighting
syntax on

" set default encoding
set encoding=utf-8

" enable backspace for insert mode
set backspace=indent,eol,start

" map ctrl-movemnet keys to window switching
map <C-k> <C-w><Up>
map <C-j> <C-w><Down>
map <C-l> <C-w><Right>
map <C-h> <C-w><Left>

" a little fix for airline plugin
set laststatus=2

" vundle setup
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" plugin manager
Bundle 'gmarik/vundle'

" file tree
Bundle 'scrooloose/nerdtree'

" preaty status line
Bundle 'bling/vim-airline'

" ^n and ^p to the tap
Bundle 'ervandew/supertab'

" Rust language support
Bundle 'wting/rust.vim'

" Git integration
Bundle 'tpope/vim-fugitive'

" auto close quotes and other symbols like (, [, etc...
Bundle "jiangmiao/auto-pairs"

" switch between html tag and other constructions
Bundle "tsaleh/vim-matchit"

" surround words with " or other symbols
Bundle 'tpope/vim-surround'

" check the syntax. supports different languages
Bundle 'scrooloose/syntastic'

" better syntax for javascript
Bundle 'jelera/vim-javascript-syntax'

" fast motion
Bundle 'Lokaltog/vim-easymotion'

" good syntax for handlebars
Bundle 'mustache/vim-mustache-handlebars'

" wakatime time management
Bundle 'wakatime/vim-wakatime'

" ack in the vim
Bundle 'mileszs/ack.vim'

" buffer explorer. Better than :ls
Bundle 'vim-scripts/bufexplorer.zip'

Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "garbas/vim-snipmate"

Bundle 'majutsushi/tagbar'
Bundle 'L9'
Bundle 'FuzzyFinder'

" shell in the vim
Bundle 'shougo/vimshell.vim'
Bundle 'shougo/vimproc'
Bundle 'vim-scripts/VimClojure'
Bundle 'briancollins/vim-jst'



filetype plugin indent on
" and of vundle
